version: '3'

services:
  mysqlsrv:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "nfe"
    ports:
      - "3306:3306"
    volumes:
      - database-data:/var/lib/mysql

volumes:
  database-data: